/**
 * Bibliothèque de formulations authentiques — invitations tunisiennes.
 * Structure inspirée des cartes traditionnelles : Bismillah, formules de courtoisie,
 * noms des familles, programme (مدني / عقد / حفلة / عشاء), remerciements.
 */
import type { InvitationCopyEntry } from "./types";

const PLACE = {
  venueAr: "قصر الورود، المرسى، تونس",
  venueFr: "Palais des Roses, La Marsa, Tunis",
  municipalityAr: "بلدية المرسى",
  municipalityFr: "Municipalité de La Marsa",
  hallAr: "قاعة الأندلس",
  hallFr: "Salle Al-Andalous",
};

const FAMILIES = {
  ar: "عائلة بن علي و عائلة طرابلسي",
  fr: "Famille Ben Ali & Famille Trabelsi",
};

const COUPLE = {
  ar: "أمينة بن علي و كريم طرابلسي",
  fr: "Amina Ben Ali & Karim Trabelsi",
};

export const COPY_LIBRARY: InvitationCopyEntry[] = [
  /* ─── MARIAGE : CLASSIQUE ─── */
  {
    id: "wedding-classic",
    category: "wedding",
    tone: "classic",
    label: "Mariage classique",
    labelAr: "زفاف كلاسيكي",
    description: "Formulation traditionnelle tunisienne — Bismillah, courtoisie, familles",
    ar: {
      bismillah: "بسم الله الرحمن الرحيم",
      heroEyebrow: "بكل فرح و سرور",
      heroTitle: "حفل زفاف أمينة و كريم",
      heroSubtitle: "يتشرف السيد محمد بن علي و السيدة فاطمة بن علي بدعوتكم لحضور حفل زفاف ابنتهما أمينة بالسيد كريم بن أحمد طرابلسي",
      quote: "وَمِنْ آيَاتِهِ أَنْ خَلَقَ لَكُمْ مِنْ أَنْفُسِكُمْ أَزْوَاجًا لِتَسْكُنُوا إِلَيْهَا",
      quoteAuthor: "سورة الروم — ٢١",
      civilTitle: "الزواج المدني",
      civilDescription: "حضوركم يسعدنا في مقر البلدية بحضور العائلة والأصدقاء.",
      contractTitle: "عقد القران و التحلية",
      contractDescription: "ببركة الله تعالى، يُقام العقد في جو من المحبة و التقوى.",
      receptionTitle: "استقبال العروسين",
      dinnerTitle: "مأدبة العشاء",
      afterTitle: "حفلة موسيقية",
      programTitle: "برنامج اليوم",
      familiesTitle: "العائلتان",
      familiesBody: "تتشرف عائلة بن علي و عائلة طرابلسي بدعوتكم لمشاركتهم فرحتهم في يوم زفاف ابنتيهما. حضوركم شرف و بهجة.",
      thanksTitle: "شكر و تقدير",
      thanksBody: "تشرفونا بحضوركم و يُرجى تأكيد المشاركة. حضوركم لنا أسمى هدية.",
      mapAddress: PLACE.venueAr,
      mapTitle: "مكان الحفل",
      countdownLabel: "متبقٍ على يوم الفرح",
    },
    fr: {
      heroEyebrow: "Ont le grand plaisir de vous inviter",
      heroTitle: "Mariage d'Amina & Karim",
      heroSubtitle: "Monsieur Mohamed Ben Ali et Madame Fatma Ben Ali ont l'honneur de vous convier à célébrer le mariage de leur fille Amina avec Monsieur Karim Trabelsi",
      quote: "Et parmi Ses signes Il a créé de vous, pour vous, des épouses pour que vous viviez en tranquillité avec elles.",
      quoteAuthor: "Coran — Sourate Ar-Rum, v. 21",
      civilTitle: "Mariage civil",
      civilDescription: "Cérémonie officielle en présence de la famille et des proches.",
      contractTitle: "Cérémonie religieuse",
      contractDescription: "Union bénie selon les traditions et sous la grâce d'Allah.",
      receptionTitle: "Réception des mariés",
      dinnerTitle: "Dîner de gala",
      afterTitle: "Soirée dansante",
      programTitle: "Programme de la journée",
      familiesTitle: "Les familles",
      familiesBody: "Les familles Ben Ali et Trabelsi ont l'honneur de vous convier à partager leur joie lors du mariage de leurs enfants. Votre présence sera pour eux un honneur.",
      thanksTitle: "Remerciements",
      thanksBody: "Votre présence sera notre plus beau cadeau. Merci de confirmer votre venue.",
      mapAddress: PLACE.venueFr,
      mapTitle: "Lieu de réception",
      countdownLabel: "Jusqu'au grand jour",
    },
    hosts: FAMILIES,
    eventName: { ar: "فرح أمينة و كريم", fr: "Mariage d'Amina & Karim" },
  },

  /* ─── MARIAGE : RELIGIEUX ─── */
  {
    id: "wedding-religious",
    category: "wedding",
    tone: "religious",
    label: "Mariage religieux",
    labelAr: "زفاف ديني",
    description: "Ton pieux — versets, baraka, formules de bénédiction",
    ar: {
      bismillah: "بسم الله الرحمن الرحيم",
      heroEyebrow: "ببركة الله و رضاه",
      heroTitle: "عقد قران و زفاف أمينة و كريم",
      heroSubtitle: "يتشرف والدا العروسين بدعوتكم لمشاركتهما هذه المناسبة المباركة",
      quote: "خَيْرُكُمْ خَيْرُكُمْ لِأَهْلِهِ",
      quoteAuthor: "حديث شريف",
      civilTitle: "الإجراءات المدنية",
      contractTitle: "عقد القران الكريم",
      contractDescription: "يُقام العقد بحضور الولي و الشهود و الدعاء بالبركة.",
      receptionTitle: "استقبال الضيوف",
      dinnerTitle: "وليمة العشاء",
      programTitle: "سير الحفل",
      familiesTitle: "بيان العائلتين",
      familiesBody: "يسعدنا دعوتكم لتشاركونا فرحة زواج مباركة. نرجو من الله أن يبارك هذا الزواج.",
      thanksTitle: "جزاكم الله خيراً",
      thanksBody: "حضوركم دعاء لنا. يُرجى تأكيد الحضور.",
      mapAddress: PLACE.venueAr,
      countdownLabel: "باقي على موعد الفرح",
    },
    fr: {
      heroEyebrow: "Sous la baraka d'Allah",
      heroTitle: "Contrat & Mariage d'Amina & Karim",
      heroSubtitle: "Les parents des mariés vous prient de bien vouloir honorer leur réjouissance",
      quote: "Les meilleurs d'entre vous sont les meilleurs envers leur famille.",
      quoteAuthor: "Hadith",
      civilTitle: "Mariage civil",
      contractTitle: "Cérémonie du contrat religieux",
      contractDescription: "Union bénie en présence de la famille et des proches.",
      receptionTitle: "Accueil des invités",
      dinnerTitle: "Repas de fête",
      programTitle: "Déroulement",
      familiesTitle: "Les deux familles",
      familiesBody: "Nous serions honorés de votre présence pour célébrer cette union bénie.",
      thanksTitle: "Remerciements",
      thanksBody: "Votre présence est une prière pour nous. Merci de confirmer.",
      mapAddress: PLACE.venueFr,
      countdownLabel: "Compte à rebours",
    },
    hosts: FAMILIES,
    eventName: { ar: "عقد و فرح أمينة و كريم", fr: "Contrat & Mariage — Amina & Karim" },
  },

  /* ─── MARIAGE : MODERNE ─── */
  {
    id: "wedding-modern",
    category: "wedding",
    tone: "modern",
    label: "Mariage moderne",
    labelAr: "زفاف عصري",
    description: "Ton contemporain, élégant et épuré",
    ar: {
      heroEyebrow: "Save the date",
      heroTitle: "أمينة & كريم",
      heroSubtitle: "نحتفل بحبنا و نود أن تكونوا معنا",
      civilTitle: "City Hall",
      contractTitle: "الاحتفال",
      receptionTitle: "Cocktail",
      dinnerTitle: "Dîner",
      afterTitle: "Party",
      programTitle: "Programme",
      familiesTitle: "مع حبنا",
      familiesBody: "معاً نكتب فصلاً جديداً. شكراً لكونكم جزءاً من قصتنا.",
      thanksTitle: "RSVP",
      thanksBody: "يرجى تأكيد حضوركم قبل الموعد.",
      mapAddress: PLACE.venueAr,
    },
    fr: {
      heroEyebrow: "Save the date",
      heroTitle: "Amina & Karim",
      heroSubtitle: "Nous célébrons notre amour et aimerions vous avoir à nos côtés",
      civilTitle: "Mairie",
      contractTitle: "Célébration",
      receptionTitle: "Cocktail",
      dinnerTitle: "Dîner",
      afterTitle: "Soirée",
      programTitle: "Programme",
      familiesTitle: "Avec amour",
      familiesBody: "Ensemble nous écrivons un nouveau chapitre. Merci de faire partie de notre histoire.",
      thanksTitle: "RSVP",
      thanksBody: "Merci de confirmer votre présence.",
      mapAddress: PLACE.venueFr,
    },
    hosts: { ar: "أمينة & كريم", fr: "Amina & Karim" },
    eventName: { ar: "أمينة & كريم", fr: "Amina & Karim" },
  },

  /* ─── MARIAGE : LUXE ─── */
  {
    id: "wedding-luxury",
    category: "wedding",
    tone: "luxury",
    label: "Mariage luxe",
    labelAr: "زفاف فاخر",
    description: "Prestige, dorure, formulation noble",
    ar: {
      bismillah: "بسم الله الرحمن الرحيم",
      heroEyebrow: "بدعوة كريمة",
      heroTitle: "حفل زفاف فاخر — أمينة و كريم",
      heroSubtitle: "يتشرف السيدان محمد بن علي و أحمد طرابلسي و زوجتيهما بدعوتكم لحضور حفل زفاف مرفرف بالمودة و المحبة",
      quote: "اللَّهُمَّ بَارِكْ لَهُمَا وَبَارِكْ عَلَيْهِمَا",
      civilTitle: "الزواج المدني",
      contractTitle: "العقد و الاحتفال",
      contractDescription: "في أجواء من الفخامة و الأناقة التونسية.",
      receptionTitle: "استقبال VIP",
      dinnerTitle: "مأدبة ملكية",
      afterTitle: "Soirée prestige",
      programTitle: "Programme exclusif",
      familiesTitle: "العائلتان الكريمتان",
      familiesBody: "يسعدنا أن نرحب بكم في هذا اليوم الاستثنائي. حضوركم يرفع من قدر المناسبة.",
      thanksTitle: "تقديرنا لكم",
      thanksBody: "نتطلع إلى استقبالكم. يُرجى تأكيد الحضور.",
      mapAddress: PLACE.venueAr,
      countdownLabel: "حتى اللحظة الذهبية",
    },
    fr: {
      heroEyebrow: "Invitation distinguée",
      heroTitle: "Mariage Prestige — Amina & Karim",
      heroSubtitle: "Monsieur Mohamed Ben Ali et Monsieur Ahmed Trabelsi et leurs épouses ont l'honneur de vous convier à une célébration d'exception",
      quote: "Que Allah bénisse leur union.",
      civilTitle: "Mariage civil",
      contractTitle: "Contrat & Célébration",
      contractDescription: "Dans un cadre d'élégance et de raffinement tunisien.",
      receptionTitle: "Réception VIP",
      dinnerTitle: "Dîner prestige",
      afterTitle: "Soirée gala",
      programTitle: "Programme",
      familiesTitle: "Les familles",
      familiesBody: "Nous serions honorés de vous accueillir pour cette journée exceptionnelle.",
      thanksTitle: "Remerciements",
      thanksBody: "Dans l'attente de vous recevoir. Merci de confirmer.",
      mapAddress: PLACE.venueFr,
      countdownLabel: "Jusqu'au jour J",
    },
    hosts: FAMILIES,
    eventName: { ar: "فرح فاخر — أمينة و كريم", fr: "Mariage Prestige — Amina & Karim" },
  },

  /* ─── MARIAGE : MINIMAL ─── */
  {
    id: "wedding-minimal",
    category: "wedding",
    tone: "minimal",
    label: "Mariage minimal",
    labelAr: "زفاف بسيط",
    description: "Épuré, essentiel, élégant",
    ar: {
      heroEyebrow: "دعوة",
      heroTitle: "أمينة & كريم",
      heroSubtitle: "زفاف — تونس",
      civilTitle: "مدني",
      contractTitle: "احتفال",
      receptionTitle: "استقبال",
      dinnerTitle: "عشاء",
      programTitle: "البرنامج",
      familiesTitle: "—",
      familiesBody: "نشكركم على مشاركتكم فرحتنا.",
      thanksTitle: "—",
      thanksBody: "تأكيد الحضور مرحب به.",
      mapAddress: PLACE.venueAr,
    },
    fr: {
      heroEyebrow: "Invitation",
      heroTitle: "Amina & Karim",
      heroSubtitle: "Mariage — Tunis",
      civilTitle: "Civil",
      contractTitle: "Célébration",
      receptionTitle: "Réception",
      dinnerTitle: "Dîner",
      programTitle: "Programme",
      familiesTitle: "—",
      familiesBody: "Merci de partager ce moment avec nous.",
      thanksTitle: "—",
      thanksBody: "Confirmation de présence appréciée.",
      mapAddress: PLACE.venueFr,
    },
    hosts: COUPLE,
    eventName: COUPLE,
  },

  /* ─── FIANÇailles ─── */
  {
    id: "engagement-classic",
    category: "engagement",
    tone: "classic",
    label: "Fiançailles classiques",
    labelAr: "خطوبة كلاسيكية",
    description: "Khotba / fiançailles tunisienne traditionnelle",
    ar: {
      bismillah: "بسم الله الرحمن الرحيم",
      heroEyebrow: "بكل سرور",
      heroTitle: "حفل خطوبة أمينة و كريم",
      heroSubtitle: "يتشرف والدا العروسين بدعوتكم لحضور حفل الخطوبة",
      civilTitle: "خطبة رسمية",
      contractTitle: "حفل الخطوبة",
      contractDescription: "تبادل الخواتم و التباري في جو عائلي.",
      receptionTitle: "استقبال",
      dinnerTitle: "عشاء عائلي",
      programTitle: "برنامج الخطوبة",
      familiesTitle: "العائلتان",
      familiesBody: "بعد مشيئة الله، تُحتفى بالخطوبة. حضوركم يسعدنا.",
      thanksTitle: "شكراً",
      thanksBody: "يرجى تأكيد الحضور.",
      mapAddress: PLACE.venueAr,
    },
    fr: {
      heroEyebrow: "Avec joie",
      heroTitle: "Fiançailles d'Amina & Karim",
      heroSubtitle: "Les parents des futurs mariés vous invitent à célébrer leurs fiançailles",
      civilTitle: "Fiançailles officielles",
      contractTitle: "Cérémonie des fiançailles",
      contractDescription: "Échange des alliances en présence de la famille.",
      receptionTitle: "Réception",
      dinnerTitle: "Dîner familial",
      programTitle: "Programme",
      familiesTitle: "Les familles",
      familiesBody: "Les familles Ben Ali et Trabelsi vous convient à cette heureuse nouvelle.",
      thanksTitle: "Remerciements",
      thanksBody: "Merci de confirmer votre présence.",
      mapAddress: PLACE.venueFr,
    },
    hosts: FAMILIES,
    eventName: { ar: "خطوبة أمينة و كريم", fr: "Fiançailles — Amina & Karim" },
  },

  /* ─── HENNÉ ─── */
  {
    id: "henna-traditional",
    category: "henna",
    tone: "traditional",
    label: "Soirée du henné",
    labelAr: "ليلة الحنة",
    description: "Laylat al-henna — tradition féminine tunisienne",
    ar: {
      heroEyebrow: "ليلة مباركة",
      heroTitle: "حفلة الحنة — أمينة",
      heroSubtitle: "تدعوكم العروس و عائلتها لحضور ليلة الحنة",
      contractTitle: "ليلة الحنة",
      contractDescription: "أغاني، حنة، زينة و فرح نسائي تونسي أصيل.",
      receptionTitle: "استقبال الإناث",
      dinnerTitle: "عشاء تقليدي",
      programTitle: "برنامج الليلة",
      familiesTitle: "مع تحيات",
      familiesBody: "ليلة الحنة من تقاليدنا الجميلة. حضوركنّ يزين الليلة.",
      thanksTitle: "—",
      thanksBody: "للنساء و الفتيات — تأكيد الحضور.",
      mapAddress: PLACE.venueAr,
    },
    fr: {
      heroEyebrow: "Soirée traditionnelle",
      heroTitle: "Henné d'Amina",
      heroSubtitle: "La mariée et sa famille vous invitent à la soirée du henné",
      contractTitle: "Soirée du henné",
      contractDescription: "Chants, henné et traditions tunisiennes.",
      receptionTitle: "Accueil",
      dinnerTitle: "Dîner traditionnel",
      programTitle: "Programme",
      familiesTitle: "Cordialement",
      familiesBody: "Une soirée réservée aux femmes et jeunes filles de la famille et amies.",
      thanksTitle: "—",
      thanksBody: "Merci de confirmer votre présence.",
      mapAddress: PLACE.venueFr,
    },
    hosts: { ar: "عائلة بن علي", fr: "Famille Ben Ali" },
    eventName: { ar: "حنة أمينة", fr: "Henné d'Amina" },
  },

  /* ─── NAISSANCE ─── */
  {
    id: "birth-classic",
    category: "birth",
    tone: "classic",
    label: "Naissance",
    labelAr: "ولادة",
    description: "Accueil du nouveau-né — سبّاح ou fête",
    ar: {
      bismillah: "بسم الله الرحمن الرحيم",
      heroEyebrow: "بفرح و سعادة",
      heroTitle: "ترحيب بالمولود الجديد — يوسف",
      heroSubtitle: "يتشرف السيدان كريم و أمينة بدعوتكم لحضور حفل السبّاح",
      receptionTitle: "استقبال",
      dinnerTitle: "وليمة",
      programTitle: "البرنامج",
      familiesTitle: "العائلة",
      familiesBody: "رزقنا الله بمولود سالم. حضوركم يبهجنا.",
      thanksTitle: "شكراً",
      thanksBody: "يرجى تأكيد الحضور.",
      mapAddress: PLACE.venueAr,
    },
    fr: {
      heroEyebrow: "Avec bonheur",
      heroTitle: "Bienvenue à bébé Youssef",
      heroSubtitle: "Karim et Amina ont le plaisir de vous inviter à la célébration de la naissance",
      receptionTitle: "Réception",
      dinnerTitle: "Repas",
      programTitle: "Programme",
      familiesTitle: "La famille",
      familiesBody: "Allah nous a béni d'un enfant en bonne santé. Votre présence nous réjouira.",
      thanksTitle: "Remerciements",
      thanksBody: "Merci de confirmer.",
      mapAddress: PLACE.venueFr,
    },
    hosts: COUPLE,
    eventName: { ar: "ولادة يوسف", fr: "Naissance de Youssef" },
  },

  /* ─── CIRCONCISION ─── */
  {
    id: "circumcision-traditional",
    category: "circumcision",
    tone: "traditional",
    label: "Circoncision",
    labelAr: "ختان",
    description: "Thtil / circoncision — célébration familiale",
    ar: {
      bismillah: "بسم الله الرحمن الرحيم",
      heroEyebrow: "ببركة الله",
      heroTitle: "حفل الختان — يوسف",
      heroSubtitle: "تدعوكم العائلة لمشاركة هذه المناسبة المباركة",
      receptionTitle: "استقبال",
      dinnerTitle: "وليمة",
      programTitle: "البرنامج",
      familiesTitle: "العائلة",
      familiesBody: "دعواتكم للدعاء لابننا بالصحة و العافية.",
      thanksTitle: "جزاكم الله خيراً",
      thanksBody: "تأكيد الحضور.",
      mapAddress: PLACE.venueAr,
    },
    fr: {
      heroEyebrow: "Sous la protection d'Allah",
      heroTitle: "Circoncision de Youssef",
      heroSubtitle: "La famille vous invite à partager cette célébration",
      receptionTitle: "Réception",
      dinnerTitle: "Repas",
      programTitle: "Programme",
      familiesTitle: "La famille",
      familiesBody: "Nous comptons sur vos prières pour la santé de notre fils.",
      thanksTitle: "Remerciements",
      thanksBody: "Merci de confirmer.",
      mapAddress: PLACE.venueFr,
    },
    hosts: FAMILIES,
    eventName: { ar: "ختان يوسف", fr: "Circoncision de Youssef" },
  },

  /* ─── DIPLÔME ─── */
  {
    id: "graduation-modern",
    category: "graduation",
    tone: "modern",
    label: "Diplôme",
    labelAr: "تخرّج",
    description: "Remise de diplôme / graduation",
    ar: {
      heroEyebrow: "بفخر",
      heroTitle: "حفل تخرّج أمينة",
      heroSubtitle: "تدعوكم العائلة للاحتفال بهذا الإنجاز",
      receptionTitle: "استقبال",
      dinnerTitle: "عشاء",
      programTitle: "البرنامج",
      familiesTitle: "—",
      familiesBody: "بعد سنوات من الجهد، نحتفل بالتخرج. شكراً لدعمكم.",
      thanksTitle: "—",
      thanksBody: "تأكيد الحضور.",
      mapAddress: PLACE.venueAr,
    },
    fr: {
      heroEyebrow: "Avec fierté",
      heroTitle: "Remise des diplômes — Amina",
      heroSubtitle: "La famille vous invite à célébrer cette réussite",
      receptionTitle: "Réception",
      dinnerTitle: "Dîner",
      programTitle: "Programme",
      familiesTitle: "—",
      familiesBody: "Après des années d'efforts, nous célébrons ce diplôme. Merci pour votre soutien.",
      thanksTitle: "—",
      thanksBody: "Merci de confirmer.",
      mapAddress: PLACE.venueFr,
    },
    hosts: FAMILIES,
    eventName: { ar: "تخرّج أمينة", fr: "Diplôme — Amina" },
  },
];

export function getCopyById(id: string): InvitationCopyEntry | undefined {
  return COPY_LIBRARY.find((c) => c.id === id);
}

export function listCopyByCategory(category: EventCategory): InvitationCopyEntry[] {
  return COPY_LIBRARY.filter((c) => c.category === category);
}

export function listCopyByTone(tone: InvitationCopyEntry["tone"]): InvitationCopyEntry[] {
  return COPY_LIBRARY.filter((c) => c.tone === tone);
}
